version: 2

updates:
  # GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: master
    assignees: [AlexNDRmac]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"

  # npm dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: master
    assignees: [AlexNDRmac]
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    versioning-strategy: increase
