version: 2

aliases:
  # CONSTANTS

  - &node_key_base node-v1-
  - &node_key node-v1-{{ checksum "package-lock.json" }}

  # CACHES

  - &restore_node_cache
    restore_cache:
      keys:
        - *node_key
        - *node_key_base

  - &save_node_cache
    save_cache:
      key: *node_key
      paths:
        - ./node_modules

  # INSTALLS
  - &node_setup
    run:
      name: NPM | Install
      command: npm install

jobs:
  build:
    docker:
      - image: circleci/node:carbon

    working_directory: ~/project

    steps:
      - checkout

      - *restore_node_cache
      - *node_setup
      - *save_node_cache

      - run:
          name: Run Postman tests
          command: |
            npx newman run PostmanAssertsInit.postman_collection.json -r cli,html,json --reporter-json-export ./postman_runner_report.json --reporter-html-export ./postman_ci_tests_report.html

      - store_artifacts:
          path: ./postman_ci_tests_report.html
          destination: postman/postman_ci_tests_report.html

      - store_artifacts:
          path: ./postman_runner_report.json
          destination: postman/postman_runner_report.json
